FROM rackspacedot/python37

RUN pip install akshare 
RUN mkdir /usr/dl
RUN cd /usr/dl
# download node
RUN wget https://npm.taobao.org/mirrors/node/v12.15.0/node-v12.15.0-linux-x64.tar.xz
RUN tar xvf node-v12.15.0-linux-x64.tar.xz
RUN mv node-v12.15.0-linux-x64 node12
# install node
# 这里卡住。。。。
RUN echo export NODE_HOME=/usr/dl/node12 >> /etc/profile
RUN echo export export PATH=$NODE_HOME:$PATH >> /etc/profile
RUN source /etc/profile

CMD [ "/bin/bash" ]

